### ISSUE TITLE
Maybe link to useful replacement?

### ISSUE THREAD

**Issue by henryiii** [andrewseidl/githook-clang-format#10]
Maybe mention https://github.com/ssciwr/clang-format-precommit? Also, you can get `clang-format` directly from PyPI now, 1-2 MB, for all common platforms, versions 10-12. See https://github.com/ssciwr/clang-format-wheel. Totally up to you. :)

**Comment by andrewseidl** [comment]
Awesome, thanks! Added.

That's pretty sweet about it now also being in PyPI, I had been dealing with some Docker images which did something similar but weren't getting updated as frequently as I'd have liked (and don't have time to maintain myself).
